accessibility:
  icons: []
  label: Accessibility
alert:
  icons: []
  label: Alert
animals:
  icons: []
  label: Animals
arrows:
  icons:
    - arrow-alt-down
    - arrow-alt-up
    - long-arrow-down
    - long-arrow-up
  label: Arrows
audio-video:
  icons:
    - circle
  label: Audio & Video
automotive:
  icons:
    - bus
    - bus-alt
    - car
    - car-side
  label: Automotive
autumn:
  icons: []
  label: Autumn
beverage:
  icons: []
  label: Beverage
buildings:
  icons: []
  label: Buildings
business:
  icons:
    - edit
    - print
  label: Business
camping:
  icons: []
  label: Camping
charity:
  icons: []
  label: Charity
chat:
  icons: []
  label: Chat
chess:
  icons: []
  label: Chess
childhood:
  icons: []
  label: Childhood
clothing:
  icons: []
  label: Clothing
code:
  icons: []
  label: Code
communication:
  icons: []
  label: Communication
computers:
  icons:
    - print
  label: Computers
construction:
  icons: []
  label: Construction
currency:
  icons:
    - pound-sign
    - sack
    - tenge
  label: Currency
date-time:
  icons:
    - clock
  label: Date & Time
design:
  icons:
    - edit
  label: Design
editors:
  icons:
    - edit
    - print
  label: Editors
education:
  icons: []
  label: Education
emoji:
  icons: []
  label: Emoji
energy:
  icons: []
  label: Energy
files:
  icons: []
  label: Files
finance:
  icons:
    - sack
  label: Finance
fitness:
  icons: []
  label: Fitness
food:
  icons: []
  label: Food
fruit-vegetable:
  icons: []
  label: Fruits & Vegetables
games:
  icons: []
  label: Games
gaming-tabletop:
  icons: []
  label: Tabletop Gaming
gender:
  icons: []
  label: Genders
halloween:
  icons: []
  label: Halloween
hands:
  icons:
    - hand-holding
  label: Hands
health:
  icons: []
  label: Health
holiday:
  icons: []
  label: Holiday
hotel:
  icons:
    - car
  label: Hotel
household:
  icons: []
  label: Household
images:
  icons: []
  label: Images
interfaces:
  icons:
    - ban
    - check
    - circle
    - edit
    - info-square
    - plus
    - times
    - user
  label: Interfaces
logistics:
  icons: []
  label: Logistics
maps:
  icons:
    - car
    - info-square
    - plus
    - print
  label: Maps
maritime:
  icons: []
  label: Maritime
marketing:
  icons: []
  label: Marketing
mathematics:
  icons:
    - plus
    - times
  label: Mathematics
medical:
  icons:
    - plus
  label: Medical
moving:
  icons: []
  label: Moving
music:
  icons: []
  label: Music
objects:
  icons:
    - bus
    - car
    - print
  label: Objects
payments-shopping:
  icons: []
  label: Payments & Shopping
pharmacy:
  icons: []
  label: Pharmacy
political:
  icons: []
  label: Political
religion:
  icons: []
  label: Religion
science:
  icons: []
  label: Science
science-fiction:
  icons: []
  label: Science Fiction
security:
  icons:
    - ban
  label: Security
shapes:
  icons:
    - circle
  label: Shapes
shopping:
  icons: []
  label: Shopping
social:
  icons:
    - user
    - user-plus
  label: Social
spinners:
  icons:
    - slash
    - spinner
    - spinner-third
  label: Spinners
sports:
  icons: []
  label: Sports
spring:
  icons: []
  label: Spring
status:
  icons:
    - ban
    - info-square
    - plus
    - print
    - user
  label: Status
summer:
  icons: []
  label: Summer
toggle:
  icons:
    - circle
  label: Toggle
travel:
  icons:
    - bus
    - bus-alt
  label: Travel
users-people:
  icons:
    - user
    - user-plus
  label: Users & People
vehicles:
  icons:
    - bus
    - bus-alt
    - car
    - car-side
  label: Vehicles
weather:
  icons: []
  label: Weather
winter:
  icons: []
  label: Winter
writing:
  icons:
    - edit
  label: Writing
