export const faArrowAltDown: IconDefinition;
export const faArrowAltUp: IconDefinition;
export const faCircle: IconDefinition;
export const faInfoSquare: IconDefinition;
export const faLongArrowDown: IconDefinition;
export const faLongArrowUp: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const far: IconPack;