export const faBan: IconDefinition;
export const faCheck: IconDefinition;
export const faEdit: IconDefinition;
export const faHandHolding: IconDefinition;
export const faPlus: IconDefinition;
export const faPoundSign: IconDefinition;
export const faSlash: IconDefinition;
export const faTenge: IconDefinition;
export const faTimes: IconDefinition;
export const faUserPlus: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const fas: IconPack;